classroom_ifpi/classroom_ifpi/urls.py
from django.contrib import admin
from django.urls import path, include
from comum.views import *
from frequencia.views import *
from horarios.views import *
from rest_framework import routers
from comum import views as comum_views
from horarios import views as horario_views
from frequencia import views as frequencia_views
from painel import views as painel_views
from qr_code import views
from rest_framework.authtoken.views import obtain_auth_token

# router = routers.DefaultRouter()
# router.register(r'aluno', AlunoDetail, base_name="alunos")
# # router.register(r'professor', ProfessorDetail, base_name="professores")
# router.register(r'disciplina', DisciplinaDetail, base_name="disciplinas")
# router.register(r'curso', CursoDetail, base_name="cursos")
# router.register(r'turma', TurmaDetail, base_name="turmas")
# router.register(r'matriculaDisciplinar', MatriculaDisciplinarDetail, base_name="matriculaDisciplinares")



urlpatterns = [
    path('admin/', admin.site.urls),
    path('qr/', include('qr_code.urls')),
    # path('', include(router.urls)),

    #URLs API
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api-token-auth/', obtain_auth_token),
    path('api/', comum_views.ApiRoot.as_view(), name=comum_views.ApiRoot.name),
    path('api/professores/<int:pk>', comum_views.ProfessorDetail.as_view(), name =comum_views.ProfessorDetail.name ),
    path('api/professores/', comum_views.ProfessorList.as_view(), name = comum_views.ProfessorList.name),
    path('api/usuarios/<int:pk>', comum_views.UserDetail.as_view(), name = comum_views.UserDetail.name),
    path('api/usuarios/', comum_views.UserList.as_view(), name = comum_views.UserList.name),
    path('api/alunos/<int:pk>', comum_views.AlunoDetail.as_view(), name = comum_views.AlunoDetail.name),
    path('api/alunos/', comum_views.AlunoList.as_view(), name = comum_views.AlunoList.name),
    path('api/cursos/<int:pk>', comum_views.CursoDetail.as_view(), name=comum_views.CursoDetail.name),
    path('api/cursos/', comum_views.CursoList.as_view(), name=comum_views.CursoList.name),
    path('api/disciplinas/<int:pk>', comum_views.DisciplinaDetail.as_view(), name=comum_views.DisciplinaDetail.name),
    path('api/disciplinas/', comum_views.DisciplinaList.as_view(), name=comum_views.DisciplinaList.name),
    path('api/turmas/<int:pk>', comum_views.TurmaDetail.as_view(), name=comum_views.TurmaDetail.name),
    path('api/turmas/', comum_views.TurmaList.as_view(), name=comum_views.TurmaList.name),
    path('api/matriculas/<int:pk>', comum_views.MatriculaDisciplinarDetail.as_view(), name=comum_views.MatriculaDisciplinarDetail.name),
    path('api/matriculas/', comum_views.MatriculaDisciplinarList.as_view(), name=comum_views.MatriculaDisciplinarList.name),
    path('api/horarios/<int:pk>', comum_views.HorarioDetail.as_view(), name=comum_views.HorarioDetail.name),
    path('api/horarios/', comum_views.HorarioList.as_view(), name = comum_views.HorarioList.name),
    path('api/declaracoes-ausencias/<int:pk>/', horario_views.DeclaracaoAusenciaDetail.as_view(), name=horario_views.DeclaracaoAusenciaDetail.name),
    path('api/declaracoes-ausencias/', horario_views.DeclaracaoAusenciaList.as_view(), name = horario_views.DeclaracaoAusenciaList.name),
    path('api/declaracoes-interesses/<int:pk>', horario_views.DeclaracaoInteresseDetail.as_view(), name=horario_views.DeclaracaoInteresseDetail.name),
    path('api/declaracoes-interesses/', horario_views.DeclaracaoInteresseList.as_view(), name=horario_views.DeclaracaoInteresseList.name),
    path('api/ausencias-interesses/<int:pk>', horario_views.AusenciaInteresseDetail.as_view(), name=horario_views.AusenciaInteresseDetail.name),
    path('api/ausencias-interesses/', horario_views.AusenciaInteresseList.as_view(), name=horario_views.AusenciaInteresseList.name),
    path('api/frequencias/<int:pk>', frequencia_views.FrequenciaDetail.as_view(), name=frequencia_views.FrequenciaDetail.name),
    path('api/frequencias/', frequencia_views.FrequenciaList.as_view(), name = frequencia_views.FrequenciaList.name),
    path('api/registros/<int:pk>', frequencia_views.RegistroDetail.as_view(), name=frequencia_views.RegistroDetail.name),
    path('api/registros/', frequencia_views.RegistroList.as_view(), name = frequencia_views.RegistroList.name),
    path('api/logado/', comum_views.CustomObtainAuthToken.as_view()),

    path('', painel_views.index, name = 'index'),
    path('painel/', painel_views.painel, name = 'painel'),
    path('painel/professores/', painel_views.list_professores, name = 'professores'),
    path('painel/cursos/', painel_views.list_cursos, name = 'cursos'),
    path('painel/cursos/novo/', painel_views.CadastrarCursoView.as_view(), name = 'add_curso'),
    path('painel/disciplinas/', painel_views.list_disciplinas, name = 'disciplinas'),
    path('painel/disciplinas/novo/', painel_views.CadastrarDisciplinaView.as_view(), name = 'add_disciplina'),
    path('painel/turmas/', painel_views.list_turmas, name = 'turmas'),
    path('painel/turmas/novo/', painel_views.CadastrarTurmaView.as_view(), name = 'add_turma'),
    path('painel/horarios/', painel_views.list_horarios, name='horarios'),
    path('painel/horarios/novo/', painel_views.CadastrarHorarioView.as_view(), name='add_horario'),
    path('painel/turmas/<int:turma_id>/', painel_views.turma_detalhe, name = 'turma_detalhe'),
    path('painel/turmas/<int:turma_id>/matricula-aluno/', painel_views.MatricularAlunoView.as_view(), name = 'matricula_aluno'),
    path('cadastro/professor/', painel_views.CadastrarProfessorView.as_view(), name = 'add_professor'),
    path('painel/aluno/novo/', painel_views.CadastrarAlunoView.as_view(), name = 'add_aluno'),
    path('painel/alunos/', painel_views.list_alunos, name = 'alunos'),
    path('login/', painel_views.login, name = 'login'),
    path('logout/', painel_views.logout, name = 'logout'),
]

classroom_ifpi/qr_code/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.home, name='home'),
    path('get_alunos', views.get_alunos, name='get_alunos'),
    path('register', views.register, name='register'),
    path('registered', views.registered, name='registered'),
    path('register_expired', views.register_expired, name='register_expired'),
    path('no_has_reg', views.no_has_reg, name='no_has_reg'),
    path('ip_blocked', views.ip_blocked, name='ip_blocked'),
    path('export', views.export, name='export'),
    path('export_to_csv', views.export_to_csv, name='export_to_csv'),
    path('permission_denied', views.permission_denied, name='permission_denied'),
    path('download_file', views.download_file, name='download_file'),
    path('browser_crash', views.browser_crash, name='browser_crash'),
]

classroom_ifpi/comum/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Curso(models.Model):
    TIPO_CURSO_CHOICES = (
        ('TN', 'Técnico'),
        ('TG', 'Tecnologia'),
        ('BA', 'Bacharel'),
        ('LI', 'Licenciatura'),
        ('ME', 'Mestrado'),
    )

    descricao = models.CharField(max_length=100, null=False, blank=False)
    tipo = models.CharField(max_length=2, null=False, blank=False, choices=TIPO_CURSO_CHOICES, )

    def __str__(self):
        return self.descricao


class Professor(models.Model):
    nome = models.CharField(max_length=100)
    matricula = models.CharField(max_length=15, null=False, blank=False)
    usuario = models.OneToOneField(User, on_delete=models.CASCADE, related_name='professor')
    cpf = models.CharField(max_length=14, null=False, blank=False)

    def __str__(self):
        return self.nome


class Disciplina(models.Model):
    descricao = models.CharField(max_length=100)
    ministrantes = models.ManyToManyField(Professor, through='Turma')

    def __str__(self):
        return self.descricao


class Aluno(models.Model):
    nome = models.CharField(max_length=100, default='', null=True)
    matricula_curso = models.CharField(max_length=12, null=False, blank=False)
    usuario = models.OneToOneField(User, on_delete=models.CASCADE, related_name='usuario')
    cpf = models.CharField(max_length=14, null=False, blank=False)
    curso = models.ForeignKey(Curso, null=False, blank=False, on_delete=models.CASCADE, related_name='cursos')

    def __str__(self):
        return self.nome


class Turma(models.Model):
    ministrante = models.ForeignKey(Professor, null=False, blank=False, on_delete=models.CASCADE, related_name='turma')
    especificacao_disciplina = models.CharField(max_length=100, null=False, blank=False)
    disciplina = models.ForeignKey(Disciplina, null=False, blank=False, on_delete=models.CASCADE, related_name='turma')
    carga_horaria = models.IntegerField()
    carga_horaria_ministrada = models.IntegerField(default=0)
    curso = models.ForeignKey(Curso, null=False, blank=False, on_delete=models.CASCADE, related_name='turma')
    alunos = models.ManyToManyField(Aluno, through='MatriculaDisciplinar')

    def __str__(self):
        return "%s - %s" % (self.especificacao_disciplina, self.curso.descricao)


class MatriculaDisciplinar(models.Model):
    SITUACAO_CHOICES = (
        ('A', 'Aprovado'),
        ('R', 'Reprovado'),
        ('C', 'Cursando'),
    )

    matricula = models.CharField(max_length=15, null=False, blank=False)
    aluno = models.ForeignKey(Aluno, null=False, blank=False, on_delete=models.CASCADE,
                              related_name='matricula_disciplinar')
    disciplina = models.ForeignKey(Turma, null=False, blank=False, on_delete=models.CASCADE,
                                   related_name='matricula_disciplinar')
    situacao = models.CharField(max_length=1, choices=SITUACAO_CHOICES, null=False, blank=False, default='C')

    def __str__(self):
        return self.aluno.nome + " - " + self.disciplina.especificacao_disciplina


class Horario(models.Model):

    DIA_SEMANA_CHOICES = (
        ('SEGUNDA', 'Segunda Feira'),
        ('TERCA', 'Terça Feira'),
        ('QUARTA', 'Quarta Feira'),
        ('QUINTA', 'Quinta Feira'),
        ('SEXTA', 'Sexta Feira'),
    )

    dia_semana = models.CharField(max_length=7, choices=DIA_SEMANA_CHOICES, null=False, blank=False )
    hora_inicio = models.TimeField()
    hora_fim = models.TimeField()
    turma = models.ForeignKey(Turma, null=False, blank=False, on_delete=models.CASCADE, related_name='horario')

    def __str__(self):
        return self.dia_semana + " de " + str(self.hora_inicio)+' as '+str(self.hora_fim)

classroom_ifpi/horarios/models.py
from django.db import models

# Create your models here.
from comum.models import Turma, Professor, Horario


class DeclaracaoAusencia(models.Model):

    justificativa = models.CharField(max_length=255, null=False, blank=False)
    professor = models.ForeignKey(Professor, null=False, blank=False, on_delete=models.CASCADE,
                                  related_name='declaracao_ausencia')
    turma = models.ForeignKey(Turma, null=False, blank=False, on_delete=models.CASCADE,
                              related_name='declaracao_ausencia')
    horario = models.ForeignKey(Horario, null=False, blank=False, on_delete=models.CASCADE,
                                related_name='declaracao_ausencia')
    data_falta = models.DateField()
    data_declaracao = models.DateField(auto_now_add=True)
    count = models.IntegerField(default=0)

    def __str__(self):
        return self.professor.nome + " - " + str(self.data_falta)


class DeclaracaoInteresse(models.Model):
    interessado = models.ForeignKey(Professor,on_delete=models.CASCADE, related_name='interessado', default='')
    turma = models.ForeignKey(Turma, null=False, blank=False, on_delete=models.CASCADE,
                                   related_name='declaracao_interessse')
    data_declaracao = models.DateField(auto_now_add=True)
    count = models.IntegerField(default=0)
    def __str__(self):
        return self.interessado.nome

class AusenciaInteresse(models.Model):
    ausencia = models.ForeignKey(DeclaracaoAusencia, null=False, blank=False, on_delete=models.CASCADE,
                                 related_name='ausencia_interesse')
    hora_inicio = models.TimeField()
    hora_fim = models.TimeField()
    status = models.BooleanField()
    interessado = models.ForeignKey(DeclaracaoInteresse,  null=False, blank=False, on_delete=models.CASCADE,
                                    related_name='ausencia_interesse')
    count = models.IntegerField(default=0)
    def __str__(self):
        return self.ausencia.declarador.ministrante

classroom_ifpi/painel/models.py
from django.db import models

# Create your models here.

classroom_ifpi/painel/forms.py
from django import forms


class CadastrarProfessorForm(forms.Form):

    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    password = forms.PasswordInput()
    confirma_password = forms.PasswordInput()
    email = forms.EmailField(required=True)
    username = forms.CharField(required=True)
    matricula = forms.CharField(required=True)


class CadastrarAlunoForm(forms.Form):

    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    matricula_curso = forms.CharField(required=True)
    curso = forms.IntegerField(required=True)
    email = forms.EmailField(required=True)


class MatricularAlunoForm(forms.Form):

    aluno = forms.IntegerField(required=True)
    turma = forms.IntegerField(required=False)


class CadastrarTurmaForm(forms.Form):

    ministrante = forms.IntegerField(required=True)
    disciplina = forms.IntegerField(required=False)
    curso = forms.IntegerField(required=False)
    carga_horaria = forms.IntegerField(required=False)


class CadastrarHorarioForm(forms.Form):

    dia_semana = forms.CharField(required=True)
    hora_inicio = forms.TimeField(required=False)
    hora_fim = forms.TimeField(required=False)
    turma = forms.IntegerField(required=False)


class CadastrarCursoForm(forms.Form):

    descricao = forms.CharField(required=True)
    tipo = forms.CharField(required=True)


class CadastrarDisciplinaForm(forms.Form):

    descricao = forms.CharField(required=True)

classroom_ifpi/horarios/views.py
from rest_framework import generics
from horarios.models import DeclaracaoAusencia, AusenciaInteresse, DeclaracaoInteresse
from horarios.serializers import *
from django.contrib.auth.models import User

# Create your views here.

class DeclaracaoAusenciaDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = DeclaracaoAusencia.objects.all()
    serializer_class = DeclaracaoAusenciaSerializer
    serializer_detail_class = DeclaracaoAusenciaSerializer
    name = 'declaracaoausencia-detail'


class DeclaracaoAusenciaList(generics.ListCreateAPIView):
    #queryset = DeclaracaoAusencia.objects.all()
    
    def get_queryset(self):
        username = self.request.query_params.get('username', None)
        if username is None:
            queryset = DeclaracaoAusencia.objects.all()
        else:
            pass
        return queryset
    serializer_class = DeclaracaoAusenciaSerializer
    name = 'declaracaoausencia-list'


class AusenciaInteresseDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = AusenciaInteresse.objects.all()
    serializer_class = AusenciaInteresseSerializer
    serializer_detail_class = AusenciaInteresseSerializer
    name = 'ausenciainteresse-detail'


class AusenciaInteresseList(generics.ListCreateAPIView):
    queryset = AusenciaInteresse.objects.all()
    serializer_class = AusenciaInteresseSerializer
    name = 'ausenciainteresse-list'


class DeclaracaoInteresseDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = DeclaracaoInteresse.objects.all()
    serializer_class = DeclaracaoInteresseSerializer
    serializer_detail_class = DeclaracaoInteresseSerializer
    name = 'declaracaointeresse-detail'


class DeclaracaoInteresseList(generics.ListCreateAPIView):
    queryset = DeclaracaoInteresse.objects.all()
    serializer_class = DeclaracaoInteresseSerializer
    name = 'declaracaointeresse-list'

classroom_ifpi/painel/templates/alert_mensagem.html
{% if messages %}
<ul>
    {% for message in messages %}
    <li>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

classroom_ifpi/painel/templates/alunos.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block 'body' %}


    <div class="card-title" align="center">
        <h5 class="grey-text">Alunos Cadastrados</h5>
    </div>
    <div class="card-content">
        {% if alunos.all.count > 0 %}
        <table class="striped centered">
            <thead>
            <tr>
                <th>Nome</th>
                <th>Matricula Curso</th>
                <th>Curso</th>
            </tr>
            </thead>

            <tbody>
            {% for aluno in alunos %}
            <tr>
                <td>{{ aluno.nome }}</td>
                <td>{{ aluno.matricula_curso }}</td>
                <td>{{ aluno.curso }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
        {% else %}
        <div class="card center" style="padding: 20px">
            <b>Nesta turma ainda nao possui alunos!</b>
        </div>
        {% endif %}
    </div>


<div class="fixed-action-btn">
  <a href="{% url 'add_aluno' %}"
     class="btn-floating btn-large red darken-4">
    <i class="fas fa-plus"></i>
  </a>
</div>
{% endblock %}

classroom_ifpi/painel/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Classroom IFPI</title>

    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.0/css/materialize.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.css">

    <!-- jQuery is required by Materialize to function -->
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.0/js/materialize.min.js"></script>


</head>
<body>

<ul id="slide-out" class="side-nav fixed">
    <div class="red darken-4 center white-text" style="padding: 10px">
        <i class="fas fa-users fa-fw fa-5x"></i>
        <h5>Classroom IFPI</h5>
    </div>
    <li>
        <a href="{% url 'turmas' %}">
            <i class="fas fa-fw fa-chalkboard-teacher"></i>
            Turmas
        </a>
    </li>
    <li>
        <a href="{% url 'disciplinas' %}">
            <i class="fas fa-fw fa-book"></i>
            Disciplinas
        </a>
    </li>
    <li>
        <a href="{% url 'cursos' %}">
            <i class="fas fa-fw fa-graduation-cap"></i>
            Cursos
        </a>
    </li>
    <li>
        <a href="{% url 'professores' %}">
            <i class="fas fa-fw fa-user-tie"></i>
            Profesores
        </a>
    </li>
    <li>
        <a href="{% url 'horarios' %}">
            <i class="fas fa-fw fa-clipboard-list"></i>
            Horários
        </a>
    </li>

    <hr>

    <li>
        <a href="{% url 'alunos' %}">
            <i class="fas fa-fw fa-user-graduate"></i>
            Alunos
        </a>
    </li>


</ul>

<nav class="red darken-4" style="padding-left: 280px;">
    <div class="nav-wrapper">
        <a href="#" style="font-size: 20pt">{{ titulo }}</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li>
                <a href="#">
                    {{ user.username }}
                </a>
            </li>
            <li><a href="#">Alterar Senha</a></li>
            <li><a href="{% url 'logout' %}">Logout</a></li>
        </ul>
    </div>
</nav>
<div class="card" style="padding-left: 270px;">

    <div>
        {% block 'body' %}
        {% endblock %}
    </div>

</div>
</body>

<script type="text/javascript">//<![CDATA[
window.onload=function(){
$(document).ready(function() {
    $('select').material_select();
});
}//]]>


</script>
</html>

classroom_ifpi/painel/templates/cadastro_disciplina.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block 'body' %}

<div class="row" style="margin: 12px; padding-bottom: 10%">
    <form class="col s6 offset-s3 center" method="post" action="{% url 'add_disciplina' %}">
        {% csrf_token %}
        <div class="row">
            <div class="row">
                <div class="input-field col s12">
                    <input id="descricao" name="descricao" type="text" class="validate">
                    <label for="descricao">Nome da disciplina:</label>
                </div>
            </div>
        </div>

        <button type="submit" class="btn">Salvar</button>
        <button type="reset" class="btn red">Cancelar</button>
    </form>
</div>

{% endblock %}

classroom_ifpi/painel/templates/cadastro_horario.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block 'body' %}

<div class="row" style="margin: 12px; padding-bottom: 10%">
    <form class="col s8 offset-s2 center" method="post" action="{% url 'add_horario' %}">
        {% csrf_token %}
        <div class="row">
            <div class="row">
                <div class="input-field col s6">
                    <select name="dia_semana" class="validate">
                        <option value="SEGUNDA">Segunda-feira</option>
                        <option value="TERCA">Terça-feira</option>
                        <option value="QUARTA">Quarta-feira</option>
                        <option value="QUINTA">Quinta-feira</option>
                        <option value="SEXTA">Sexta-feira</option>
                    </select>
                    <label>Dia da Semana</label>
                </div>
                <div class="input-field col s6">
                    <input id="hora_inicio" name="hora_inicio" type="time" class="validate">
                    <label for="hora_inicio">Hora de Início</label>
                </div>
                <div class="input-field col s6">
                    <input id="hora_fim" name="hora_fim" type="time" class="validate">
                    <label for="hora_fim">Hora de Fim</label>
                </div>
                <div class="input-field col s12">
                    <select name="turma" class="validate" required>
                      {% for turma in turmas %}
                        <option value="{{ turma.id }}">{{ turma }}</option>
                      {% endfor %}
                    </select>
                    <label>Turma</label>
                </div>
            </div>
        </div>

        <button type="submit" class="btn">Salvar</button>
        <button type="reset" class="btn red">Cancelar</button>
    </form>
</div>

{% endblock %}

classroom_ifpi/painel/templates/cadastro_matricula.html
{% extends 'base.html' %}
{% block 'body' %}
<div class="row" style="margin: 12px; padding-bottom: 25%">
    <form class="col s8 offset-s2 center" method="post" action="{% url 'matricula_aluno' turma.id %}">
        {% csrf_token %}
        <h5>
            <span>Matricule alunos em  </span>{{ turma.especificacao_disciplina }}
        </h5>
        <br>
        <hr>
        <br>
        <div class="row">
            <div class="input-field col s12">
                <select name="aluno" class="validate">
                    {% for aluno in alunos %}
                        <option value="{{ aluno.id }}">{{ aluno.nome }} - {{ aluno.matricula_curso }}</option>
                    {% endfor %}
                </select>
                <label>Nome do aluno:</label>
            </div>
        </div>

        <button class="btn">Matricular</button>
    </form>
</div>
{% endblock %}

classroom_ifpi/painel/templates/cadastro_professor.html
{% extends "base_registro.html" %}

{% block container %}
<!--
<div class="row">
    {% include 'alert_mensagem.html' %}
</div>-->
<div class="row">
    <div class="col s12 m8 offset-m2">
      <div class="card">
        <form method="post" action="{% url 'add_professor' %}">
          {% csrf_token %}
          <div class="card-content">
              <div align="center" class="card-title">
                  <h5 class="grey-text">Cadastro de Professor</h5>
              </div>

              <div class="row">
                  <div class="input-field col s6">
                    <i class="material-icons prefix fas fa-user"></i>
                    <input name="first_name" type="text" class="validate">
                    <label>Nome</label>
                  </div>
                  <div class="input-field col s6">
                    <i class="material-icons prefix fas fa-user"></i>
                    <input name="last_name" type="text" class="validate">
                    <label>Sobrenome</label>
                  </div>
                  <div class="input-field col s6">
                    <i class="material-icons prefix fas fa-id-card"></i>
                    <input name="matricula" type="text" class="validate">
                    <label>Matricula</label>
                  </div>
                  <div class="input-field col s6">
                    <i class="material-icons prefix fas fa-envelope"></i>
                    <input name="email" type="email" class="validate">
                    <label>Email</label>
                  </div>
                  <div class="input-field col s12">
                    <i class="material-icons prefix fas fa-at"></i>
                    <input name="username" type="text" class="validate">
                    <label>Nome de Usuário</label>
                  </div>
                  <div class="input-field col s6">
                    <i class="material-icons prefix fas fa-lock"></i>
                    <input name="password" type="password" class="validate">
                    <label>Senha</label>
                  </div>
                  <div class="input-field col s6">
                    <i class="material-icons prefix fas fa-lock"></i>
                    <input name="confirma_password" type="password" class="validate">
                    <label>Confirmar Senha</label>
                  </div>
              </div>
          </div>
          <div align="center" class="card-action">
              <button class="btn waves-effect waves-light" type="submit">Salvar</button>
              <button class="btn waves-effect red darken-4 waves-light" type="reset">Cancelar</button>
          </div>
          <div align="center" class="card-content">
               <a href="{% url 'login' %}">Já tenho conta. Entrar!</a>
          </div>
        </form>
      </div>
    </div>
</div>
{% endblock container %}

classroom_ifpi/painel/templates/cadastro_turma.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block 'body' %}

<div class="row" style="margin: 12px; padding-bottom: 25%">
    <form class="col s8 offset-s2 center" method="post" action="{% url 'add_turma' %}">
        {% csrf_token %}
        <div class="row">
            <div class="row">
                <div class="input-field col s6">
                    <select name="ministrante" class="validate">
                        {% for ministrante in professores %}
                        <option value="{{ ministrante.id }}">{{ ministrante }}</option>
                        {% endfor %}
                    </select>
                    <label>Professor</label>
                </div>
                <div class="input-field col s6">
                    <input id="carga_horaria" name="carga_horaria" type="number" class="validate" required>
                    <label for="carga_horaria">Carga Horaria</label>
                </div>
            </div>

            <div class="row">
                <div class="input-field col s6">
                    <select name="curso" class="validate">
                        {% for curso in cursos %}
                        <option value="{{ curso.id }}">{{ curso }}</option>
                        {% endfor %}
                    </select>
                    <label>Curso</label>
                </div>

                <div class="input-field col s6">
                    <select name="disciplina" class="validate">
                        {% for disciplina in disciplinas %}
                        <option value="{{ disciplina.id }}">{{ disciplina }}</option>
                        {% endfor %}
                    </select>
                    <label>Disciplina</label>
                </div>
            </div>
        </div>

        <button type="submit" class="btn">Salvar</button>
        <button type="reset" class="btn red">Voltar</button>
    </form>
</div>

{% endblock %}

classroom_ifpi/painel/templates/cursos.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block 'body' %}
<div style="padding-right: 20px;">
    <div class="row">
        <ul class="col s8 offset-s2 collection">
            {% for curso in cursos %}
            <li class="collection-item avatar">
                <i class="material-icons circle green">
                    <i class="fas fa-graduation-cap"></i>
                </i>
                <b class="title">{{ curso.descricao }}</b>
                <p>{{ curso.get_tipo_display }}<br>
                </p>
                <a href="#!" class="secondary-content"><i class="material-icons">
                    <i class="fas fa-star"></i>
                </i></a>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>


<div class="fixed-action-btn">
    <a href="{% url 'add_curso' %}"
       class="btn-floating btn-large red darken-4">
        <i class="fas fa-plus"></i>
    </a>
</div>
{% endblock %}